# Generated by Django 4.2 on 2023-10-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
